title: 'Éƒitlabs'
description: "Decentralised ecosystem studio"
baseurl: "/"
url: "https://bitlabs.dev"

header_pages:
  - index.md
  - about.md
  - contact.md

style: light 

footer: 'follow us on <a href="https://twitter.com/_bitlabs">twitter</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
